//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ObjectWithList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectWithList")
#ifdef RESTRICT_ObjectWithList
#define INCLUDE_ALL_ObjectWithList 0
#else
#define INCLUDE_ALL_ObjectWithList 1
#endif
#undef RESTRICT_ObjectWithList

#if !defined (ObjectWithList_) && (INCLUDE_ALL_ObjectWithList || defined(INCLUDE_ObjectWithList))
#define ObjectWithList_

@protocol JavaUtilList;

@interface ObjectWithList : NSObject {
 @public
  id<JavaUtilList> integers_;
}

#pragma mark Public

- (instancetype)init;

- (id<JavaUtilList>)getIntegers;

@end

J2OBJC_EMPTY_STATIC_INIT(ObjectWithList)

J2OBJC_FIELD_SETTER(ObjectWithList, integers_, id<JavaUtilList>)

FOUNDATION_EXPORT void ObjectWithList_init(ObjectWithList *self);

FOUNDATION_EXPORT ObjectWithList *new_ObjectWithList_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ObjectWithList *create_ObjectWithList_init();

J2OBJC_TYPE_LITERAL_HEADER(ObjectWithList)

#endif

#pragma pop_macro("INCLUDE_ALL_ObjectWithList")
