//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ProtocolTest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ProtocolTest")
#ifdef RESTRICT_ProtocolTest
#define INCLUDE_ALL_ProtocolTest 0
#else
#define INCLUDE_ALL_ProtocolTest 1
#endif
#undef RESTRICT_ProtocolTest

#if !defined (ProtocolTest_) && (INCLUDE_ALL_ProtocolTest || defined(INCLUDE_ProtocolTest))
#define ProtocolTest_

@interface ProtocolTest : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)isCollectionAssignableFromList;

@end

J2OBJC_EMPTY_STATIC_INIT(ProtocolTest)

FOUNDATION_EXPORT void ProtocolTest_init(ProtocolTest *self);

FOUNDATION_EXPORT ProtocolTest *new_ProtocolTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ProtocolTest *create_ProtocolTest_init();

FOUNDATION_EXPORT jboolean ProtocolTest_isCollectionAssignableFromList();

J2OBJC_TYPE_LITERAL_HEADER(ProtocolTest)

#endif

#pragma pop_macro("INCLUDE_ALL_ProtocolTest")
